name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: worker_test
        - run: docker build -t stulast/worker -f Dockerfile.dev ./worker
        - run: docker run  -e CI=true stulast/worker npm test
      
      - name: client_test
        - run: docker build -t stulast/client -f client/Dockerfile.dev ./client
        - run: docker run  -e CI=true stulast/tesdt npm test

      - name: api_test
        - run: docker build -t stulast/api -f client/Dockerfile.dev ./api
        - run: docker run  -e CI=true stulast/api npm test
      


      # - name: Generate deployment package
      #   run: zip -r deploy.zip . -x '*.git'

      # - name: Deploy to EBS
      #   uses: einaregilsson/beanstalk-deploy@v20
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: demo-docker
      #     environment_name: Demodocker-env
      #     existing_bucket_name: elasticbeanstalk-eu-west-2-046560510837
      #     region: eu-west-2
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip
